### PR TITLE
feat(package): change commitplease to commitizen

### PR DESCRIPTION
**Pull request by spentacular**
## Description of change

I was checking out commitplease which somehow lead me to [Commitizen](http://commitizen.github.io/cz-cli/#making-your-repo-commitizen-friendly). [Here's a video](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-writing-conventional-commits-with-commitizen) about it as well.

This uses the Angular commit message style through the other plugin: cz-conventional-changelog

Commitplease may even still work better but still wanted to PR just so you could check side-by-side.

This only changes the dependencies and run scripts, no code changes.

### Pull request (PR) check-list

> **:white_check_mark: Please review and check the appropriate items.**

1. **Type of change**
    - [ ] BREAKING CHANGE (with documentation) _Please explain if selected_
    - [ ] Chore
    - [ ] Defect (bug) fix (with regression tests)
    - [ ] Documentation
    - [x] Feature/enhancement (with JavaDocs and/or Wiki article(s))
    - [ ] Hotfix (with documentation)
    - [ ] Performance improvement (with benchmarks)
    - [ ] Refactoring (with catalog reference)
    - [ ] Reversion
    - [ ] Tests
2. **Code standards compliance**
    - [ ] Yes, `ESLint` passes.
    - [x] N/A (not applicable): _Please explain if selected_
3. **Code quality**. Do the quality gateways pass with an "A" grade?
    - [ ] `Complexity`
    - [ ] `Duplications` (0.00%)
    - [ ] `Issues` (0 issues or documentation for "won't fix" cases)
    - [ ] `Maintainability`/`Technical Debt`
    - [ ] `Reliability`
    - [ ] `Security`
    - [x] N/A (not applicable). _Please explain if selected_
4. **Test coverage**
    - [ ] The source code is 100% covered with passing specs.
    - [x] N/A (not applicable). _Please explain if selected_

> **:information_source: These tasks are not required to open a PR and can be done afterwards, or while the PR is open.**

### CODE REVIEW

**Comment by gregswindle** [comment]
Hi, @spentacular, I'm open to this. Could you please review the proposal with @mkorat1717 -- y'all are in the same building 😄 -- and go from there. 

I was originally thinking we could _suggest_ commitzen be installed globally, but if commitzen can also enforce the AngularJS Git Commit Convention with a pre-commit hook, I'm open to the change.

**Comment by spentacular** [comment]
@gregswindle I was getting some clashing with both the commitizen & commitplease co-existing via a precommit hook, but I'll look into it to see what is causing the clash. It may have to be a post-commit hook, which would be grosser and cause a lot more confusion than good I think.

**Comment by gregswindle** [comment]
If `commitzen` does pre-commit hooks, let's use that instead of `commitplease`. If not -- or if it's hard to configure -- let's keep `commitplease`. The whole idea here is to enforce a commit convention that enables semantic release automation.

If, however, you can figure out a way to install `commitzen` _globally_ along with this generator, that might be the best of both worlds. I was thinking of creating something like a `generator-commitizen` (if it doesn't already exist) that we could compose all vz-specific generators with.

**Review by gregswindle — COMMENTED** [review]
If commitzen does pre-commit hooks, let's use that instead of commitplease. If not -- or if it's hard to configure -- let's keep commitplease. The whole idea here is to enforce a commit convention that enables semantic release automation.

If, however, you can figure out a way to install commitzen globally along with this generator, that might be the best of both worlds. I was thinking of creating something like a generator-commitizen (if it doesn't already exist) that we could compose all vz-specific generators with.

**Comment by spentacular** [comment]
So would the intent be you run `git commit` and the precommit hook runs, dropping into the commitizen mode and then using that as the commit?

I added a `npm run commit` which will do a commit with commitizen, but it's also not a hook, so it wouldn't run automatically.

Here's what commitizen + commitplease looks like (with my custom aliases)

```bash
generator-android-lib develop ∴ echo 'testing' > test.md
generator-android-lib develop  ☡ ∴ gs
## develop...origin/develop
?? test.md
generator-android-lib develop  ☡ ∴ ga
generator-android-lib develop + ∴ git cz
cz-cli@2.9.6, cz-conventional-changelog@1.2.0


Line 1 will be cropped at 100 characters. All other lines will be wrapped after 100 characters.

? Select the type of change that you're committing: feat:     A new feature
? Denote the scope of this change ($location, $browser, $compile, etc.):
 
? Write a short, imperative tense description of the change:
 
? Provide a longer description of the change:
 
? List any breaking changes or issues closed by this change:
 
Invalid commit message, please fix:

- First line must be <type>(<scope>): <subject>
Need an opening parenthesis: (

Commit message was:

feat:

See https://bit.ly/angular-guidelines
/usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:102
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/commitizen/dist/git/commit.js:50:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

The blanks on the ? lines are me not entering any information into commitizen. It throws an error and reverts out of the commit just like normal.

The problem now is the script `npm run commit` triggers the precommit hook too early, causing an error, so it would need to run under a different name in order to use them in tandem.

**Comment by gregswindle** [comment]
@spentacular I'm going to close this PR. Feel free to reopen it should the urge arise :relieved:.

**Pull request closed without merging**
